### ISSUE TITLE
Unable to install @olton/aptos

### ISSUE THREAD

**Issue by cryptowithvickaiah** [olton/aptos-api#1]
i want to thank you for your time, kindly look into this thanks.
Below is the error message when i run this command 'npm install --save @olton/aptos'

npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@olton%2faptos - Not found
npm ERR! 404
npm ERR! 404  '@olton/aptos@*' is not in this registry.
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\BitJaro\AppData\Local\npm-cache\_logs\2022-11-16T17_28_35_408Z-debug-0.log

**Comment by olton** [comment]
https://www.npmjs.com/package/@olton/aptos-api

try `npm install --save @olton/aptos-api`

**Comment by cryptowithvickaiah** [comment]
Thanks man
